---
title: "Data Visualization to House Price Advanced Regression train.csv Data"
author: "Dhyka"
date: "11/16/2021"
output: html_document
---

## Assignment

```{r}
#Preaparation step
library(tidyverse)
library(readr)
```

We will use the Ames Housing dataset for the assignment.

```{r}
ames <- read_csv('train.csv')
```

```{r}
glimpse(ames)
```

Gain & visualize 4 insights from the Ames housing dataset

1. Count of one categorical feature
```{r}
ames %>%
  count(HouseStyle) %>%
  ggplot(aes(x = HouseStyle, y = n)) +
  geom_bar(stat = 'identity', width=.5, fill="tomato3") +
  geom_label(aes(label = n)) +
    labs(title = "House Style in Boston",
       subtitle = "What trend developt in Boston on term of dwelling style?",
       caption = "source:kaggle",
       x="House Style category",
       y="Count of every category") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```


2. Distribution of one continuous feature
```{r}
ggplot(ames,aes(SalePrice)) +
  geom_density(aes(fill = Street)) +
  scale_color_manual(values = c("#868686FF", "#EFC000FF")) +
  geom_vline(aes(xintercept = mean(SalePrice)), linetype = "dashed") +
  labs(title = "Density of the Sale Price of House on Boston",
       subtitle = "How much the density of house selling price in Boston grouped by Street type?",
       caption = "source:kaggle",
       x="Sale Price",
       y="Density") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```

3. Categorical-continuous
```{r}
ggplot(ames,aes(HouseStyle,SalePrice, color = HouseStyle)) +
  geom_boxplot() +
  labs(title = "Relation between House Style and Sale Price ",
       subtitle = "How the influence of House Style can affect the house selling price?",
       caption = "source:kaggle",
       x="Dwelling Style",
       y="House Selling Price") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```


4. Continuous-continuous
```{r}
ggplot(ames,aes(SalePrice,LotArea)) +
  geom_point(aes(colour = factor(LotShape))) +
  labs(title = "Relation between Sale Price and Lot Area",
       subtitle = "How the property size can affect the house selling price grouped by the property shape?",
       caption = "source:kaggle",
       x="House Selling Price",
       y="Property Size (sqf)") +
  theme(axis.text.x = element_text(angle=65, vjust=0.6))
```